version: '3.8'

services:
  # Database Services
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ev91user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-EV91SecurePass2025!}
      POSTGRES_DB: ${POSTGRES_DB:-ev91platform}
      POSTGRES_MULTIPLE_DATABASES: spare_parts,auth,teams,vehicles,clients,riders
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ev91user} -d ${POSTGRES_DB:-ev91platform}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ev91-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - ev91-network

  # Core Services
  api-gateway:
    build:
      context: ../apps/api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${API_GATEWAY_PORT:-8000}:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ev91user}:${POSTGRES_PASSWORD:-EV91SecurePass2025!}@postgres:5432/${POSTGRES_DB:-ev91platform}?schema=api_gateway
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-super-secret-jwt-key-for-ev91-platform-change-in-production-2025}
      - AUTH_SERVICE_URL=http://auth-service:3001
      - TEAM_SERVICE_URL=http://team-service:3002
      - CLIENT_STORE_SERVICE_URL=http://client-store-service:3003
      - VEHICLE_SERVICE_URL=http://vehicle-service:4004
      - RIDER_SERVICE_URL=http://rider-service:3004
      - SPARE_PARTS_SERVICE_URL=http://spare-parts-service:4006
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000,http://localhost:8080
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX_REQUESTS=1000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../apps/api-gateway:/app
      - /app/node_modules
    networks:
      - ev91-network

  # Authentication Service
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ev91user}:${POSTGRES_PASSWORD:-EV91SecurePass2025!}@postgres:5432/${POSTGRES_DB:-ev91platform}?schema=auth
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-super-secret-jwt-key-for-ev91-platform-change-in-production-2025}
      - JWT_EXPIRES_IN=24h
      - BCRYPT_ROUNDS=10
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../services/auth-service:/app
      - /app/node_modules
    networks:
      - ev91-network

  # Spare Parts Service
  spare-parts-service:
    build:
      context: ../services/spare-parts-service
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "${SPARE_PARTS_PORT:-4006}:4006"
    environment:
      - NODE_ENV=development
      - PORT=4006
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ev91user}:${POSTGRES_PASSWORD:-EV91SecurePass2025!}@postgres:5432/${POSTGRES_DB:-ev91platform}?schema=spare_parts
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-super-secret-jwt-key-for-ev91-platform-change-in-production-2025}
      - AUTH_SERVICE_URL=http://auth-service:3001
      - VEHICLE_SERVICE_URL=http://vehicle-service:4004
      - CLIENT_STORE_SERVICE_URL=http://client-store-service:3003
      - API_VERSION=v1
      - LOG_LEVEL=info
      - UPLOAD_DIR=/app/uploads/spare-parts
      - MAX_FILE_SIZE=10485760
      - ALLOWED_FILE_TYPES=image/jpeg,image/png,image/webp,application/pdf
      - LOW_STOCK_THRESHOLD=10
      - CRITICAL_STOCK_THRESHOLD=5
      - AUTO_REORDER_ENABLED=false
      - DEFAULT_MARKUP_PERCENTAGE=20
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - FROM_EMAIL=noreply@ev91platform.com
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_started
    volumes:
      - ../services/spare-parts-service:/app
      - /app/node_modules
      - spare_parts_uploads:/app/uploads/spare-parts
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4006/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ev91-network

  # Supporting Services for Spare Parts Development
  vehicle-service:
    build:
      context: ../services/vehicle-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=4004
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ev91user}:${POSTGRES_PASSWORD:-EV91SecurePass2025!}@postgres:5432/${POSTGRES_DB:-ev91platform}?schema=vehicles
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-super-secret-jwt-key-for-ev91-platform-change-in-production-2025}
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_started
    volumes:
      - ../services/vehicle-service:/app
      - /app/node_modules
    networks:
      - ev91-network

  client-store-service:
    build:
      context: ../services/client-store-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ev91user}:${POSTGRES_PASSWORD:-EV91SecurePass2025!}@postgres:5432/${POSTGRES_DB:-ev91platform}?schema=clients
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-super-secret-jwt-key-for-ev91-platform-change-in-production-2025}
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_started
    volumes:
      - ../services/client-store-service:/app
      - /app/node_modules
    networks:
      - ev91-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  spare_parts_uploads:
    driver: local

networks:
  ev91-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
