apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
  namespace: ev91
  labels:
    app: rider-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
      - name: rider-service
        image: ev91/rider-service:latest
        ports:
        - containerPort: 4002
        env:
        - name: PORT
          value: "4002"
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ev91-db-secrets
              key: rider-service-db-url
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: ev91-twilio-secrets
              key: account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ev91-twilio-secrets
              key: auth-token
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: ev91-twilio-secrets
              key: phone-number
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 4002
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4002
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: ev91
spec:
  selector:
    app: rider-service
  ports:
  - port: 4002
    targetPort: 4002
  type: ClusterIP
